# Configuration Netlify pour MIDEESSI

[build]
  publish = "dist"
  command = "npm run build"

# Variables d'environnement pour le build
[build.environment]
  NODE_VERSION = "18"

# IMPORTANT : Les redirections avec conditions User-Agent
# Pour les crawlers de réseaux sociaux, proxy vers le serveur SEO Render
# L'URL reste mideessi.com mais le contenu vient de Render

# Facebook
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["facebookexternalhit*", "Facebot*"]}

# Twitter
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["Twitterbot*"]}

# LinkedIn
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["LinkedInBot*"]}

# WhatsApp
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["WhatsApp*"]}

# Slack
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["Slackbot*"]}

# Discord
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["Discordbot*"]}

# Pinterest
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["Pinterest*"]}

# Google
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["Googlebot*"]}

# Bing
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["bingbot*"]}

# Telegram
[[redirects]]
  from = "/blog/*"
  to = "https://mideessi-seo.onrender.com/blog/:splat"
  status = 200
  force = true
  conditions = {User-Agent = ["TelegramBot*"]}

# Pour TOUS les autres visiteurs (navigateurs normaux)
# Servir le SPA React normalement
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"