/**
 * Centralized Route Paths for MIDEESSI
 */
export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  MISSION: '/mission',
  METHODE: '/methode',
  TEAM_MEMBER: '/team/:id',
  SOLUTIONS: '/solutions',
  SOLUTION_SITEWEB: '/solution/siteweb',
  SOLUTION_SITEWEB_DETAIL: '/solution/siteweb/:slug',
  SOLUTION_DETAIL: '/solutions/:slug',
  PROJECTS: '/projects',
  ATELIERS: '/ateliers',
  ATELIER_DETAIL: '/ateliers/:slug',
  OFFRES: '/offres',
  OFFRES_DETAIL: '/offres/:slug',
  DEV_SERVICES_DETAIL: '/dev-services/:slug',
  BLOG: '/article',
  BLOG_POST: '/article/:slug',
  APPRENDRE: '/apprendre',
  FORMATION_DETAIL: '/apprendre/formations/:slug',
  LABORATOIRE: '/laboratoire',
  LABS: '/labs',
  LIBRARY: '/library',
  LIBRARY_DETAIL: '/library/:id',
  LIBRARY_READ: '/library/:id/read',
  COMMANDER: '/commander',
  COMMANDER_DETAIL: '/commander/:offerSlug',
  CLIENT_PROJECTS: '/clients/projets',
  CLIENT_PROJECT_DETAIL: '/clients/projets/:id',
  CLIENTS: '/clients',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  MY_LIBRARY: '/my-library',
  PROFILE_OVERVIEW: '/profile/:username',
  SEARCH_PROFILES: '/search-profiles',
  USER_PROFILE_EDIT: '/profile/edit',
  SUBMIT_DOSSIER: '/submit-dossier',
  CLIENT_ONBOARDING: '/clients/onboarding',
  CLIENT_DASHBOARD: '/clients/dashboard',
  CLIENT_LIVRABLES: '/clients/livrables',
  CLIENT_MESSAGES: '/clients/messages',
  CLIENT_FACTURES: '/clients/factures',
  CLIENT_COMPTE: '/clients/compte',
  CLIENT_INFOS: '/clients/infos',
  CLIENT_KPIS: '/clients/kpis',
  CLIENT_CALENDAR: '/clients/calendar',
  CLIENT_REPORTS: '/clients/reports',
  CLIENT_QUOTES: '/clients/quotes',
  CLIENT_DOSSIERS: '/clients/dossiers',
  CLIENT_OBJECTIVES: '/clients/objectives',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_SOLUTIONS: '/admin/solutions',
  ADMIN_CLIENTS: '/admin/clients',
  ADMIN_PROJECTS: '/admin/projets',
  ADMIN_PDFS: '/admin/pdfeditor',
  ADMIN_QUOTES: '/admin/quotes',
  SHARE_REDIRECT: '/share/:slug',
  ADMIN_POST_EDIT: '/admin/post/:id',
  CONTACT: '/contact',
  LEGAL: '/legal',
};

export const getRoute = {
  home: () => '/',
  about: () => '/about',
  mission: () => '/mission',
  methode: () => '/methode',
  teamMember: (id: string | number) => `/team/${id}`,
  solutions: () => '/solutions',
  solutionSiteweb: () => '/solution/siteweb',
  solutionSitewebDetail: (slug: string) => `/solution/siteweb/${slug}`,
  solutionDetail: (slug: string) => `/solutions/${slug}`,
  projects: () => '/projects',
  ateliers: () => '/ateliers',
  atelierDetail: (slug: string) => `/ateliers/${slug}`,
  offres: () => '/offres',
  offresDetail: (slug: string) => `/offres/${slug}`,
  devServicesDetail: (slug: string) => `/dev-services/${slug}`,
  blog: () => '/article',
  blogPost: (slug: string) => `/article/${slug}`,
  apprendre: () => '/apprendre',
  laboratoire: () => '/laboratoire',
  labs: () => '/laboratoire',
  library: () => '/library',
  libraryDetail: (id: string | number) => `/library/${id}`,
  libraryRead: (id: string | number) => `/library/${id}/read`,
  commander: () => '/commander',
  commanderDetail: (offerSlug: string) => `/commander/${offerSlug}`,
  clientProjects: () => '/clients/projets',
  clientProjectDetail: (id: string | number) => `/clients/projets/${id}`,
  clients: () => '/clients',
  login: () => '/login',
  signup: () => '/signup',
  forgotPassword: () => '/forgot-password',
  resetPassword: () => '/reset-password',
  myLibrary: () => '/my-library',
  profileOverview: (username: string) => `/profile/${username}`,
  searchProfiles: () => '/search-profiles',
  userProfileEdit: () => '/profile/edit',
  submitDossier: () => '/submit-dossier',
  clientOnboarding: () => '/clients/onboarding',
  clientDashboard: () => '/clients/dashboard',
  clientLivrables: () => '/clients/livrables',
  clientMessages: () => '/clients/messages',
  clientFactures: () => '/clients/factures',
  clientCompte: () => '/clients/compte',
  clientInfos: () => '/clients/infos',
  clientKpis: () => '/clients/kpis',
  clientCalendar: () => '/clients/calendar',
  clientReports: () => '/clients/reports',
  clientQuotes: () => '/clients/quotes',
  clientDossiers: () => '/clients/dossiers',
  clientObjectives: () => '/clients/objectives',
  adminDashboard: () => '/admin/dashboard',
  adminSolutions: () => '/admin/solutions',
  adminClients: () => '/admin/clients',
  adminProjects: () => '/admin/projets',
  adminPdfs: () => '/admin/pdfeditor',
  adminQuotes: () => '/admin/quotes',
  shareRedirect: (slug: string) => `/share/${slug}`,
  adminPostEdit: (id: string | number) => `/admin/post/${id}`,
  contact: () => '/contact',
  legal: () => '/legal',
};
